// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsTtELia2l50ILcPBA31ioLZypKnUfx2Q',
    appId: '1:285744189463:web:b47d55c4754b5b2908cc52',
    messagingSenderId: '285744189463',
    projectId: 'in-memory-3ebcc',
    authDomain: 'in-memory-3ebcc.firebaseapp.com',
    storageBucket: 'in-memory-3ebcc.appspot.com',
    measurementId: 'G-X5FFPFSLJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKV9Ol989o9OVTf3exSELrw_5rJGozno4',
    appId: '1:285744189463:android:642582f16f305a6b08cc52',
    messagingSenderId: '285744189463',
    projectId: 'in-memory-3ebcc',
    storageBucket: 'in-memory-3ebcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN9S4PCPJmRUA-VjARt2HvbSDOipPMOmE',
    appId: '1:285744189463:ios:f0f28a616adc3e1a08cc52',
    messagingSenderId: '285744189463',
    projectId: 'in-memory-3ebcc',
    storageBucket: 'in-memory-3ebcc.appspot.com',
    iosBundleId: 'com.gulftechinnovations.inMemory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN9S4PCPJmRUA-VjARt2HvbSDOipPMOmE',
    appId: '1:285744189463:ios:5787f4a82870113808cc52',
    messagingSenderId: '285744189463',
    projectId: 'in-memory-3ebcc',
    storageBucket: 'in-memory-3ebcc.appspot.com',
    iosBundleId: 'com.gulftechinnovations.inMemory.RunnerTests',
  );
}
